modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="coordosy"
version="${file.jarVersion}"
displayName="Coordosy"
issueTrackerURL="github.com/bookking3000/Coordosy/issues"
description='''
A Minecraft Mod indicating the Direction to another Player
'''
